server:
  port: 8888

spring:
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_URI:http://localhost:8787}
  cloud:
    gateway:
      routes:
        - id: discovery-service-route
          uri: lb://discovery-service
          predicates:
            - Path=/api/v1/discovery/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
