server:
  port: 8085

spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5439/order_db}
    username: ${ORDER_DB_USERNAME:order_db}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.dogac.common_events.event,com.dogac.common_events.enums"
        spring.json.use.type.headers: true
