server:
  port: 8081

spring:
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5436/product_db}
    username: ${PRODUCT_DB_USERNAME:product_db}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.dogac.common_events.event,com.dogac.common_events.enums"
        spring.json.use.type.headers: true
