#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jan 29 15:11:07 GMT+03:00 2026
maven-metadata-spring-snapshots.xml.lastUpdated=1769688667860
