spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8787
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5437/user_db
    username: user_db
    password: user-password
    driver-class-name: org.postgresql.Driver

server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
